# This file is named "travis.sample.yml".
# Rename it ".travis.yml".
# http://docs.travis-ci.com/user/build-configuration/ 

sudo: required

# blacklist
branches:
  except:
    - master
    - zach

# whitelist
#branches:
#  only:
#    - dev

language: python

python:
    - "3.4"

before_install:
    - sudo apt-get update

install:
    - pip install --upgrade pip

before_script:
    - uname -a
    - printenv
    - pip3 --version
    - pip3 freeze
    - python3 --version

script:
    - date

    # - ls -al
    # - touch IDB.log
    # - make models.html
    - ls -al
    - make requirements
    - python3 proj3site/manage.py makemigrations populate_content
    - make unittest
